<?php

return [
    'return_types' => [
        'getUpdates'                      => 'Array of Update',
        'setWebhook'                      => 'Boolean',
        'deleteWebhook'                   => 'Boolean',
        'getWebhookInfo'                  => 'WebhookInfo',
        'getMe'                           => 'User',
        'logOut'                          => 'Boolean',
        'close'                           => 'Boolean',
        'sendMessage'                     => 'Message',
        'forwardMessage'                  => 'Message',
        'copyMessage'                     => 'MessageId',
        'sendPhoto'                       => 'Message',
        'sendAudio'                       => 'Message',
        'sendDocument'                    => 'Message',
        'sendVideo'                       => 'Message',
        'sendAnimation'                   => 'Message',
        'sendVoice'                       => 'Message',
        'sendVideoNote'                   => 'Message',
        'sendMediaGroup'                  => 'Array of Message',
        'sendLocation'                    => 'Message',
        'editMessageLiveLocation'         => 'Message or Boolean',
        'stopMessageLiveLocation'         => 'Message or Boolean',
        'sendVenue'                       => 'Message',
        'sendContact'                     => 'Message',
        'sendPoll'                        => 'Message',
        'sendDice'                        => 'Message',
        'sendChatAction'                  => 'Boolean',
        'getUserProfilePhotos'            => 'UserProfilePhotos',
        'getFile'                         => 'File',
        'banChatMember'                   => 'Boolean',
        'unbanChatMember'                 => 'Boolean',
        'restrictChatMember'              => 'Boolean',
        'promoteChatMember'               => 'Boolean',
        'setChatAdministratorCustomTitle' => 'Boolean',
        'banChatSenderChat'               => 'Boolean',
        'unbanChatSenderChat'             => 'Boolean',
        'setChatPermissions'              => 'Boolean',
        'exportChatInviteLink'            => 'String',
        'createChatInviteLink'            => 'ChatInviteLink',
        'editChatInviteLink'              => 'ChatInviteLink',
        'revokeChatInviteLink'            => 'ChatInviteLink',
        'approveChatJoinRequest'          => 'Boolean',
        'declineChatJoinRequest'          => 'Boolean',
        'setChatPhoto'                    => 'Boolean',
        'deleteChatPhoto'                 => 'Boolean',
        'setChatTitle'                    => 'Boolean',
        'setChatDescription'              => 'Boolean',
        'pinChatMessage'                  => 'Boolean',
        'unpinChatMessage'                => 'Boolean',
        'unpinAllChatMessages'            => 'Boolean',
        'leaveChat'                       => 'Boolean',
        'getChat'                         => 'Chat',
        'getChatAdministrators'           => 'ChatMember[]',
        'getChatMemberCount'              => 'Integer',
        'getChatMember'                   => 'ChatMember',
        'setChatStickerSet'               => 'Boolean',
        'deleteChatStickerSet'            => 'Boolean',
        'answerCallbackQuery'             => 'Boolean',
        'setMyCommands'                   => 'Boolean',
        'deleteMyCommands'                => 'Boolean',
        'getMyCommands'                   => 'Array of BotCommand',
        'setChatMenuButton'               => 'Boolean',
        'getChatMenuButton'               => 'MenuButton',
        'setMyDefaultAdministratorRights' => 'Boolean',
        'getMyDefaultAdministratorRights' => 'ChatAdministratorRights',
        'editMessageText'                 => 'Message or Boolean',
        'editMessageCaption'              => 'Message or Boolean',
        'editMessageMedia'                => 'Message or Boolean',
        'editMessageReplyMarkup'          => 'Message or Boolean',
        'stopPoll'                        => 'Poll',
        'deleteMessage'                   => 'Boolean',
        'sendSticker'                     => 'Message',
        'getStickerSet'                   => 'StickerSet',
        'uploadStickerFile'               => 'File',
        'createNewStickerSet'             => 'Boolean',
        'addStickerToSet'                 => 'Boolean',
        'setStickerPositionInSet'         => 'Boolean',
        'deleteStickerFromSet'            => 'Boolean',
        'setStickerSetThumb'              => 'Boolean',
        'answerInlineQuery'               => 'Boolean',
        'answerWebAppQuery'               => 'SentWebAppMessage',
        'sendInvoice'                     => 'Message',
        'answerShippingQuery'             => 'Boolean',
        'answerPreCheckoutQuery'          => 'Boolean',
        'setPassportDataErrors'           => 'Boolean',
        'sendGame'                        => 'Message',
        'setGameScore'                    => 'Message or Boolean',
        'getGameHighScores'               => 'Array of GameHighScore',
    ],

    'replace' => [
        'InputFile' => 'Tii\\Telepath\\Types\\InputFile',
    ],

    'ignore_types' => [
        'InputFile',
    ]
];
